"""empty message

Revision ID: 013945d1005d
Revises: b8a4877218da
Create Date: 2019-09-30 04:46:30.301749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013945d1005d'
down_revision = 'b8a4877218da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table_choices = op.create_table('choices',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    tabel_genres = op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    choices=[
        ('AL', 'AL'),
        ('AK', 'AK'),
        ('AZ', 'AZ'),
        ('AR', 'AR'),
        ('CA', 'CA'),
        ('CO', 'CO'),
        ('CT', 'CT'),
        ('DE', 'DE'),
        ('DC', 'DC'),
        ('FL', 'FL'),
        ('GA', 'GA'),
        ('HI', 'HI'),
        ('ID', 'ID'),
        ('IL', 'IL'),
        ('IN', 'IN'),
        ('IA', 'IA'),
        ('KS', 'KS'),
        ('KY', 'KY'),
        ('LA', 'LA'),
        ('ME', 'ME'),
        ('MT', 'MT'),
        ('NE', 'NE'),
        ('NV', 'NV'),
        ('NH', 'NH'),
        ('NJ', 'NJ'),
        ('NM', 'NM'),
        ('NY', 'NY'),
        ('NC', 'NC'),
        ('ND', 'ND'),
        ('OH', 'OH'),
        ('OK', 'OK'),
        ('OR', 'OR'),
        ('MD', 'MD'),
        ('MA', 'MA'),
        ('MI', 'MI'),
        ('MN', 'MN'),
        ('MS', 'MS'),
        ('MO', 'MO'),
        ('PA', 'PA'),
        ('RI', 'RI'),
        ('SC', 'SC'),
        ('SD', 'SD'),
        ('TN', 'TN'),
        ('TX', 'TX'),
        ('UT', 'UT'),
        ('VT', 'VT'),
        ('VA', 'VA'),
        ('WA', 'WA'),
        ('WV', 'WV'),
        ('WI', 'WI'),
        ('WY', 'WY'),
    ]

    values = [{'id': tp[0], 'name': tp[1]} for tp in choices]

    op.bulk_insert(table_choices, values)

    choices=[
        'Alternative',
        'Blues',
        'Classical',
        'Country',
        'Electronic',
        'Folk',
        'Funk',
        'Hip-Hop',
        'Heavy Metal',
        'Instrumental',
        'Jazz',
        'Musical Theatre',
        'Pop',
        'Punk',
        'R&B',
        'Reggae',
        'Rock n Roll',
        'Soul',
        'Other',
    ]

    values = [{'name': tp} for tp in choices]

    op.bulk_insert(tabel_genres, values)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genres')
    op.drop_table('choices')
    # ### end Alembic commands ###
